apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-api
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tech-challenge.orbithr.com.br`)
      kind: Rule
      services:
        - name: backend-api
          port: 80
  tls:
    secretName: cloudflare-cert
